# These are supported funding model platforms

github: banfbi
patreon: banfbi
open_collective: banfbi
ko_fi: banfbi
tidelift: banfbi
community_bridge: banfbi
liberapay: banfbi
issuehunt: banfbi
lfx_crowdfunding: banfbi
polar: banfbi
buy_me_a_coffee: banfbi
custom: banfbi
